config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/' => 'recipes#index'

  resources :recipes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = MarleySpoon::Recipe.all.reverse
    @recipe = @recipes.first
  end

  def show
    @recipe = MarleySpoon::Recipe.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marley Spoon Coding Challenge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%# Borrowed from https://tailwindcss.com/docs/installation %>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="px-40 pb-40">
      <%= yield %>
    </div>
  </body>
</html>

app/views/recipes/_header.html.erb
<a href="/">
  <h1 style="font-family: 'Pacifico' !important; color: #f72585;" class="text-center text-6xl mt-20 mb-12">Yum 😋</h1>
<a>

app/views/recipes/index.html.erb
<%= render "header" %>

<div class="flex flex-row flex-wrap">
  <% @recipes.each do |recipe| %>
      <div style="flex-basis: 33%" class="p-12 flex-initial">
        <a href="<%= recipe_path(recipe.id) %>">
          <img class="rounded-lg shadow" src="<%= recipe.photo_url %>" />
          <p class="my-2 text-lg"><%= recipe.title %></p>
        </a>
      </div>
  <% end %>
</div>

app/views/recipes/show.html.erb
<%= render "header" %>

<h2 class="text-3xl mt-20 mb-4 text-center"><%= @recipe.title %></h1>

<p class="mt-12 text-lg text-justify"><%= @recipe.description %></p>

<div class="relative">
  <img class="rounded-lg mt-12 shadow" style="width: 100%;" src="<%= @recipe.photo_url %>" />

  <% if @recipe.chef_name %>
    <p style="background-color: rgba(255, 255, 255, 0.9); color: black;" class="absolute top-4 left-4 pt-1 pb-1 pl-4 pr-4 rounded-full">Designed with ❤️ by chef <%= @recipe.chef_name %></p>
  <% end %>  

  <ul class="absolute top-4 right-4 whitespace-nowrap">
    <% @recipe.tag_names.each do |tag_name| %>
      <li style="background-color: rgba(0, 0, 0, 0.5); color: white;" class="inline pt-1 pb-1 pl-4 pr-4 mr-0.5 mt-0.5 rounded-full"><%= tag_name %></li>
    <% end %>
  </ul>
</div>